const STORAGE_KEY = 'splitmate-local-v1';
const CATEGORIES = ['Food', 'Rent', 'Travel', 'Shopping', 'Bills', 'Education', 'Entertainment', 'Health', 'Other'];
const ICONS = { Food: '🍽️', Rent: '🏠', Travel: '🚆', Shopping: '🛍️', Bills: '💡', Education: '📚', Entertainment: '🎬', Health: '💊', Other: '📌' };
const money = new Intl.NumberFormat('en-IN', { style: 'currency', currency: 'INR', minimumFractionDigits: 0, maximumFractionDigits: 2 });
const dateFormat = new Intl.DateTimeFormat('en-IN', { day: '2-digit', month: 'short', year: 'numeric' });
const monthFormat = new Intl.DateTimeFormat('en-IN', { month: 'short', year: 'numeric' });

const monthKey = (date = new Date()) => `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, '0')}`;
const today = () => new Date().toISOString().slice(0, 10);
const number = (value) => { const n = Number(value); return Number.isFinite(n) ? n : 0; };
const amount = (value) => Math.max(0, number(value));
const id = (prefix) => `${prefix}_${Date.now()}_${Math.random().toString(36).slice(2, 8)}`;
const currency = (value) => money.format(number(value));
const validDate = (value) => /^\d{4}-\d{2}-\d{2}$/.test(value || '') && !Number.isNaN(new Date(`${value}T00:00:00`).getTime());
const dateLabel = (value) => validDate(value) ? dateFormat.format(new Date(`${value}T00:00:00`)) : '—';
const monthLabel = (key) => /^\d{4}-\d{2}$/.test(key || '') ? monthFormat.format(new Date(Number(key.slice(0, 4)), Number(key.slice(5)) - 1, 1)) : 'Current month';
const esc = (value = '') => String(value).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;').replace(/'/g, '&#039;');

const freshState = () => ({ settings: { currency: 'INR', darkMode: false, currentUser: 'Akash', currentMonth: monthKey() }, budgets: {}, expenses: [], groups: [], sharedExpenses: [], settlements: [] });
const normalize = (raw) => {
  const base = freshState();
  const data = raw && typeof raw === 'object' ? raw : {};
  const settings = data.settings && typeof data.settings === 'object' ? data.settings : {};
  return {
    settings: { ...base.settings, ...settings, currency: 'INR', currentUser: String(settings.currentUser || 'Akash').trim() || 'Akash', currentMonth: /^\d{4}-\d{2}$/.test(settings.currentMonth) ? settings.currentMonth : base.settings.currentMonth },
    budgets: data.budgets && typeof data.budgets === 'object' && !Array.isArray(data.budgets) ? data.budgets : {},
    expenses: Array.isArray(data.expenses) ? data.expenses : [],
    groups: Array.isArray(data.groups) ? data.groups : [],
    sharedExpenses: Array.isArray(data.sharedExpenses) ? data.sharedExpenses : [],
    settlements: Array.isArray(data.settlements) ? data.settlements : []
  };
};
const load = () => { try { const raw = localStorage.getItem(STORAGE_KEY); return normalize(raw ? JSON.parse(raw) : null); } catch (error) { console.warn('SplitMate storage reset:', error); return freshState(); } };
const save = (state) => { try { localStorage.setItem(STORAGE_KEY, JSON.stringify(normalize(state))); return true; } catch (error) { console.error('Unable to save SplitMate data:', error); toast('Could not save data in this browser.'); return false; } };
const toast = (message) => { const el = document.getElementById('toast'); if (!el) return; el.textContent = message; el.classList.add('visible'); clearTimeout(toast.timer); toast.timer = setTimeout(() => el.classList.remove('visible'), 2300); };
const months = () => { const now = new Date(); const result = []; for (let i = -6; i <= 6; i += 1) { const d = new Date(now.getFullYear(), now.getMonth() + i, 1); const key = monthKey(d); result.push({ key, label: monthLabel(key) }); } return result; };
const expensesIn = (state, key) => state.expenses.filter((item) => String(item.date || '').startsWith(key));

// Positive balances mean a person should receive money; negative balances mean they owe money.
const balances = (state, groupId = null) => {
  const result = {};
  const shared = state.sharedExpenses.filter((item) => !groupId || item.groupId === groupId);
  shared.forEach((item) => {
    const people = [...new Set((Array.isArray(item.participants) ? item.participants : []).map((p) => String(p).trim()).filter(Boolean))];
    if (!people.length && item.paidBy) people.push(String(item.paidBy).trim());
    const total = amount(item.amount);
    const share = people.length ? total / people.length : 0;
    people.forEach((person) => { result[person] = number(result[person]) - share; });
    if (item.paidBy) result[item.paidBy] = number(result[item.paidBy]) + total;
  });
  // A completed settlement moves value from the debtor to the creditor.
  state.settlements.filter((item) => item.settled && (!groupId || item.groupId === groupId)).forEach((item) => {
    const value = amount(item.amount); if (!value || !item.from || !item.to) return;
    result[item.from] = number(result[item.from]) + value;
    result[item.to] = number(result[item.to]) - value;
  });
  return result;
};
const suggestions = (raw) => {
  const debtors = Object.entries(raw).filter(([, value]) => value < -0.001).map(([person, value]) => ({ person, value: -value }));
  const creditors = Object.entries(raw).filter(([, value]) => value > 0.001).map(([person, value]) => ({ person, value }));
  const result = []; let d = 0; let c = 0;
  while (d < debtors.length && c < creditors.length) { const value = Math.min(debtors[d].value, creditors[c].value); if (value > 0.001) result.push({ from: debtors[d].person, to: creditors[c].person, amount: value }); debtors[d].value -= value; creditors[c].value -= value; if (debtors[d].value <= 0.001) d++; if (creditors[c].value <= 0.001) c++; }
  return result;
};

function setTheme(dark) { document.body.classList.toggle('dark', Boolean(dark)); document.getElementById('themeIcon').textContent = dark ? '☀️' : '🌙'; }
function fillMonths() { const state = load(); const html = months().map((m) => `<option value="${m.key}">${m.label}</option>`).join(''); ['monthSelector', 'expenseMonthFilter'].forEach((idName) => { const el = document.getElementById(idName); el.innerHTML = html; el.value = state.settings.currentMonth; }); }
function fillGroups() { const state = load(); document.getElementById('splitGroup').innerHTML = '<option value="">No group</option>' + state.groups.map((g) => `<option value="${esc(g.id)}">${esc(g.name)}</option>`).join(''); }
function stats(state) { const list = expensesIn(state, state.settings.currentMonth); const spent = list.reduce((sum, item) => sum + amount(item.amount), 0); const budget = amount(state.budgets[state.settings.currentMonth]); return { list, spent, budget, remaining: budget - spent }; }

function renderDashboard() {
  const state = load(); const data = stats(state); const userBalance = number(balances(state)[state.settings.currentUser]);
  document.getElementById('monthSelector').value = state.settings.currentMonth;
  document.getElementById('budgetAmountInput').value = data.budget || '';
  document.getElementById('budgetValue').textContent = currency(data.budget); document.getElementById('spentValue').textContent = currency(data.spent); document.getElementById('remainingValue').textContent = currency(data.remaining); document.getElementById('expenseCountValue').textContent = data.list.length;
  const balance = document.getElementById('sharedBalanceDisplay'); balance.classList.remove('positive', 'negative');
  if (Math.abs(userBalance) < 0.001) { balance.textContent = 'Settled'; document.getElementById('sharedBalanceHint').textContent = 'No outstanding split balance for your account.'; }
  else if (userBalance > 0) { balance.textContent = `You are owed ${currency(userBalance)}`; balance.classList.add('positive'); document.getElementById('sharedBalanceHint').textContent = `${state.settings.currentUser} is owed by others.`; }
  else { balance.textContent = `You owe ${currency(Math.abs(userBalance))}`; balance.classList.add('negative'); document.getElementById('sharedBalanceHint').textContent = `${state.settings.currentUser} has an outstanding share.`; }
  const list = document.getElementById('recentExpensesList'); const recent = [...data.list].sort((a, b) => String(b.date).localeCompare(String(a.date))).slice(0, 5);
  list.innerHTML = recent.length ? recent.map((e) => `<li class="mini-item"><div class="row-between"><strong>${esc(e.name)}</strong><span class="amount-pill">${currency(e.amount)}</span></div><div class="expense-meta"><span>${esc(e.category || 'Other')}</span><span>${dateLabel(e.date)}</span></div></li>`).join('') : '<li class="empty-state">No expenses yet for this month.</li>';
}
function renderExpenses() {
  const state = load(); const search = document.getElementById('expenseSearch').value.trim().toLowerCase(); const category = document.getElementById('expenseCategoryFilter').value; const selected = document.getElementById('expenseMonthFilter').value;
  const list = state.expenses.filter((e) => String(e.date || '').startsWith(selected) && (category === 'All' || (e.category || 'Other') === category) && (!search || String(e.name || '').toLowerCase().includes(search) || String(e.note || '').toLowerCase().includes(search))).sort((a, b) => String(b.date).localeCompare(String(a.date)));
  document.getElementById('expenseList').innerHTML = list.length ? list.map((e) => `<div class="expense-item"><div class="expense-item-top"><div class="expense-title"><span class="category-badge">${ICONS[e.category] || ICONS.Other}</span><div><div>${esc(e.name)}</div><div class="expense-meta"><span>${dateLabel(e.date)}</span><span>${esc(e.category || 'Other')}</span></div></div></div><span class="amount-pill">${currency(e.amount)}</span></div>${e.note ? `<div class="expense-meta"><span>${esc(e.note)}</span></div>` : ''}<div class="expense-actions"><button class="action-button" data-action="edit-expense" data-id="${esc(e.id)}" type="button">Edit</button><button class="action-button delete" data-action="delete-expense" data-id="${esc(e.id)}" type="button">Delete</button></div></div>`).join('') : '<div class="empty-state">No expenses yet. Add your first expense to start tracking.</div>';
}
function renderSplit() {
  const state = load(); const raw = balances(state); const names = [...new Set([...Object.keys(raw), ...state.groups.flatMap((g) => g.members || []), state.settings.currentUser])]; const visible = names.filter((name) => Math.abs(number(raw[name])) > 0.001);
  const summary = document.getElementById('splitSummary'); const balanceHtml = visible.length ? visible.map((name) => `<div class="balance-item"><strong>${esc(name)}</strong><span class="amount-pill ${raw[name] > 0 ? 'positive' : 'negative'}">${raw[name] > 0 ? currency(raw[name]) + ' owed' : currency(Math.abs(raw[name])) + ' due'}</span></div>`).join('') : '<div class="empty-state">No shared expenses yet. Split your first expense with friends.</div>';
  const history = [...state.sharedExpenses].sort((a, b) => String(b.date).localeCompare(String(a.date))).map((e) => `<div class="settlement-item"><div class="settlement-top"><strong>${esc(e.description || 'Shared expense')}</strong><span class="amount-pill">${currency(e.amount)}</span></div><div class="expense-meta"><span>Paid by ${esc(e.paidBy)}</span><span>${esc((e.participants || []).join(', '))}</span><span>${dateLabel(e.date)}</span></div><div class="expense-actions"><button class="action-button delete" data-action="delete-shared" data-id="${esc(e.id)}" type="button">Delete</button></div></div>`).join('');
  summary.innerHTML = balanceHtml + (history ? `<h4>Recorded shared expenses</h4>${history}` : '');
  const settlementList = document.getElementById('settlementList'); settlementList.innerHTML = state.settlements.length ? state.settlements.slice().sort((a, b) => String(b.date).localeCompare(String(a.date))).map((e) => `<div class="settlement-item"><div class="settlement-top"><div><strong>${esc(e.from)}</strong> → <strong>${esc(e.to)}</strong></div><span class="settlement-status ${e.settled ? 'settled' : 'pending'}">${e.settled ? 'Settled' : 'Pending'}</span></div><div class="row-between"><span class="amount-pill">${currency(e.amount)}</span><span>${dateLabel(e.date)}</span></div><div class="expense-actions"><button class="action-button" data-action="toggle-settlement" data-id="${esc(e.id)}" type="button">${e.settled ? 'Reopen' : 'Mark as settled'}</button><button class="action-button delete" data-action="delete-settlement" data-id="${esc(e.id)}" type="button">Delete</button></div></div>`).join('') : '<div class="empty-state">No settlement history yet.</div>';
}
function renderGroups() {
  const state = load(); const target = document.getElementById('groupList');
  target.innerHTML = state.groups.length ? state.groups.map((group) => { const groupBalances = balances(state, group.id); const groupExpenses = state.sharedExpenses.filter((e) => e.groupId === group.id); const total = groupExpenses.reduce((sum, e) => sum + amount(e.amount), 0); const members = [...new Set(group.members || [])]; const rows = members.map((person) => { const paid = groupExpenses.filter((e) => e.paidBy === person).reduce((sum, e) => sum + amount(e.amount), 0); const shares = groupExpenses.reduce((sum, e) => { const people = [...new Set(e.participants || [])]; return sum + (people.includes(person) && people.length ? amount(e.amount) / people.length : 0); }, 0); const net = number(groupBalances[person]); return `<div class="member-row"><span class="member-name">${esc(person)}</span><div class="expense-meta"><span>Paid ${currency(paid)}</span><span>Share ${currency(shares)}</span><span class="amount-pill ${net >= 0 ? 'positive' : 'negative'}">${net >= 0 ? 'Owed' : 'Due'} ${currency(Math.abs(net))}</span></div></div>`; }).join(''); const suggested = suggestions(groupBalances).map((s) => `<div class="member-row"><span>${esc(s.from)} → ${esc(s.to)}</span><span class="amount-pill">${currency(s.amount)}</span></div>`).join('') || '<div class="empty-state">No outstanding balances.</div>'; return `<div class="group-card"><div class="group-meta"><h4>${esc(group.name)}</h4><span>${groupExpenses.length} shared expense(s)</span></div><div class="group-meta"><span>Total group spend: <strong>${currency(total)}</strong></span></div><div class="member-list">${rows || '<div class="empty-state">No members.</div>'}</div><h4>Suggested settlements</h4><div class="member-list">${suggested}</div></div>`; }).join('') : '<div class="empty-state">No groups yet. Create a group for roommates or classmates.</div>';
}
function renderStatistics() { const state = load(); const list = expensesIn(state, state.settings.currentMonth); const total = list.reduce((s, e) => s + amount(e.amount), 0); document.getElementById('totalSpendingStat').textContent = currency(total); document.getElementById('largestExpenseStat').textContent = currency(list.length ? Math.max(...list.map((e) => amount(e.amount))) : 0); document.getElementById('averageExpenseStat').textContent = currency(list.length ? total / list.length : 0); document.getElementById('expenseNumberStat').textContent = list.length; const categories = {}; list.forEach((e) => { categories[e.category || 'Other'] = number(categories[e.category || 'Other']) + amount(e.amount); }); const sorted = Object.entries(categories).sort((a, b) => b[1] - a[1]); document.getElementById('categoryChart').innerHTML = sorted.length ? sorted.map(([name, value]) => `<div class="category-row"><div class="category-label"><span>${esc(name)}</span><strong>${currency(value)}</strong></div><div class="bar-track"><span class="bar-fill" style="width:${(value / sorted[0][1]) * 100}%"></span></div></div>`).join('') : '<div class="empty-state">No spending data for this month.</div>'; document.getElementById('monthlyHistory').innerHTML = months().slice(-6).map((m) => `<div class="history-item"><span>${m.label}</span><strong>${currency(expensesIn(state, m.key).reduce((s, e) => s + amount(e.amount), 0))}</strong></div>`).join(''); }
function renderSettings() { const state = load(); document.getElementById('currentUserInput').value = state.settings.currentUser; document.getElementById('currencySelect').value = 'INR'; setTheme(state.settings.darkMode); }
function renderAll() { fillMonths(); fillGroups(); renderSettings(); renderDashboard(); renderExpenses(); renderSplit(); renderGroups(); renderStatistics(); }

function submitExpense(event) { event.preventDefault(); const state = load(); const name = document.getElementById('expenseName').value.trim(); const value = amount(document.getElementById('expenseAmount').value); const date = document.getElementById('expenseDate').value; if (!name) return toast('Expense name cannot be empty.'); if (!(value > 0)) return toast('Amount must be greater than zero.'); if (!validDate(date)) return toast('Please choose a valid date.'); const form = document.getElementById('expenseForm'); const editId = form.dataset.editId; const item = { id: editId || id('expense'), name, amount: value, category: document.getElementById('expenseCategory').value || 'Other', date, note: document.getElementById('expenseNote').value.trim(), createdAt: new Date().toISOString() }; const index = state.expenses.findIndex((e) => e.id === editId); if (index >= 0) state.expenses[index] = item; else state.expenses.push(item); state.settings.currentMonth = date.slice(0, 7); save(state); form.reset(); delete form.dataset.editId; document.getElementById('expenseFormTitle').textContent = 'Add expense'; document.getElementById('cancelExpenseEdit').classList.add('hidden'); renderAll(); toast('Expense saved.'); }
function submitSplit(event) { event.preventDefault(); const state = load(); const description = document.getElementById('splitDescription').value.trim(); const value = amount(document.getElementById('splitAmount').value); const paidBy = document.getElementById('splitPaidBy').value.trim(); const date = document.getElementById('splitDate').value; const people = [...new Set([paidBy, ...document.getElementById('splitParticipants').value.split(',').map((p) => p.trim()).filter(Boolean)])]; if (!description) return toast('Please enter a description.'); if (!(value > 0)) return toast('Amount must be greater than zero.'); if (!paidBy) return toast('Please add the payer name.'); if (!validDate(date)) return toast('Please enter a valid date.'); state.sharedExpenses.push({ id: id('split'), description, amount: value, paidBy, participants: people, groupId: document.getElementById('splitGroup').value, date, createdAt: new Date().toISOString() }); state.settings.currentMonth = date.slice(0, 7); save(state); document.getElementById('splitForm').reset(); renderAll(); toast('Shared expense saved.'); }
function submitSettlement(event) { event.preventDefault(); const from = document.getElementById('settlementFrom').value.trim(); const to = document.getElementById('settlementTo').value.trim(); const value = amount(document.getElementById('settlementAmount').value); const date = document.getElementById('settlementDate').value; if (!from || !to || from === to) return toast('Enter two different people.'); if (!(value > 0)) return toast('Settlement amount must be greater than zero.'); if (!validDate(date)) return toast('Choose a valid settlement date.'); const state = load(); state.settlements.push({ id: id('settlement'), from, to, amount: value, date, settled: false, createdAt: new Date().toISOString() }); save(state); document.getElementById('settlementForm').reset(); renderAll(); toast('Settlement added.'); }
function submitGroup(event) { event.preventDefault(); const name = document.getElementById('groupName').value.trim(); const members = [...new Set(document.getElementById('groupMembers').value.split(',').map((p) => p.trim()).filter(Boolean))]; if (!name) return toast('Group name is required.'); if (!members.length) return toast('Add at least one member name.'); const state = load(); if (state.groups.some((g) => String(g.name).toLowerCase() === name.toLowerCase())) return toast('A group with this name already exists.'); state.groups.push({ id: id('group'), name, members, createdAt: new Date().toISOString() }); save(state); document.getElementById('groupForm').reset(); renderAll(); toast('Group created.'); }
function saveBudget(event) { event.preventDefault(); const state = load(); const raw = document.getElementById('budgetAmountInput').value; if (raw === '' || number(raw) < 0) return toast('Budget must be zero or greater.'); state.budgets[state.settings.currentMonth] = amount(raw); save(state); renderAll(); toast('Monthly budget saved.'); }

function loadDemo() { const current = monthKey(); const previous = monthKey(new Date(new Date().getFullYear(), new Date().getMonth() - 1, 1)); save({ settings: { currency: 'INR', darkMode: false, currentUser: 'Akash', currentMonth: current }, budgets: { [current]: 9000, [previous]: 8000 }, expenses: [{ id: 'demo-1', name: 'Mess lunch', amount: 540, category: 'Food', date: `${current}-02`, note: 'Campus food' }, { id: 'demo-2', name: 'Metro pass', amount: 320, category: 'Travel', date: `${current}-07`, note: 'Recharge' }, { id: 'demo-3', name: 'Book purchase', amount: 850, category: 'Education', date: `${current}-12`, note: '' }], groups: [{ id: 'demo-group', name: 'Roommates', members: ['Akash', 'Rahul', 'Aman', 'Priya'] }], sharedExpenses: [{ id: 'demo-split-1', description: 'Dinner', amount: 1200, paidBy: 'Akash', participants: ['Akash', 'Rahul', 'Aman'], groupId: 'demo-group', date: `${current}-09` }, { id: 'demo-split-2', description: 'Groceries', amount: 1800, paidBy: 'Rahul', participants: ['Akash', 'Rahul', 'Aman', 'Priya'], groupId: 'demo-group', date: `${current}-14` }], settlements: [] }); renderAll(); toast('Demo data loaded.'); }
function exportData() { const blob = new Blob([JSON.stringify(load(), null, 2)], { type: 'application/json' }); const url = URL.createObjectURL(blob); const link = document.createElement('a'); link.href = url; link.download = 'splitmate-backup.json'; link.click(); URL.revokeObjectURL(url); toast('Data exported.'); }
async function importData(event) { const file = event.target.files && event.target.files[0]; if (!file) return; try { const parsed = JSON.parse(await file.text()); if (!parsed || typeof parsed !== 'object' || Array.isArray(parsed)) throw new Error('Invalid backup'); if (!Array.isArray(parsed.expenses) || !Array.isArray(parsed.sharedExpenses) || !Array.isArray(parsed.groups) || !Array.isArray(parsed.settlements)) throw new Error('Invalid backup shape'); save(parsed); renderAll(); toast('Data imported successfully.'); } catch (error) { toast('Invalid JSON backup. Existing data was kept.'); } event.target.value = ''; }

function handleActions(event) { const button = event.target.closest('[data-action]'); if (!button) return; const state = load(); const action = button.dataset.action; const itemId = button.dataset.id; if (action === 'edit-expense') { const e = state.expenses.find((x) => x.id === itemId); if (!e) return; document.getElementById('expenseName').value = e.name; document.getElementById('expenseAmount').value = e.amount; document.getElementById('expenseCategory').value = e.category || 'Other'; document.getElementById('expenseDate').value = e.date; document.getElementById('expenseNote').value = e.note || ''; document.getElementById('expenseForm').dataset.editId = itemId; document.getElementById('expenseFormTitle').textContent = 'Edit expense'; document.getElementById('cancelExpenseEdit').classList.remove('hidden'); document.querySelector('[data-view="expenses"]').click(); document.getElementById('expenseName').focus(); } else if (action === 'delete-expense') { const e = state.expenses.find((x) => x.id === itemId); if (e && confirm(`Delete "${e.name}"?`)) { state.expenses = state.expenses.filter((x) => x.id !== itemId); save(state); renderAll(); toast('Expense deleted.'); } } else if (action === 'delete-shared') { if (confirm('Delete this shared expense? Balances will be recalculated.')) { state.sharedExpenses = state.sharedExpenses.filter((x) => x.id !== itemId); save(state); renderAll(); toast('Shared expense deleted.'); } } else if (action === 'toggle-settlement') { const e = state.settlements.find((x) => x.id === itemId); if (e) { e.settled = !e.settled; save(state); renderAll(); toast(e.settled ? 'Settlement marked as settled.' : 'Settlement reopened.'); } } else if (action === 'delete-settlement') { state.settlements = state.settlements.filter((x) => x.id !== itemId); save(state); renderAll(); toast('Settlement deleted.'); } }

function bind() {
  document.getElementById('themeToggle').onclick = () => { const state = load(); state.settings.darkMode = !state.settings.darkMode; save(state); setTheme(state.settings.darkMode); };
  document.getElementById('settingsThemeToggle').onclick = () => document.getElementById('themeToggle').click();
  document.getElementById('monthSelector').onchange = (e) => { const state = load(); state.settings.currentMonth = e.target.value; save(state); renderAll(); };
  document.getElementById('expenseMonthFilter').onchange = renderExpenses; document.getElementById('expenseSearch').oninput = renderExpenses; document.getElementById('expenseCategoryFilter').onchange = renderExpenses;
  document.getElementById('budgetForm').onsubmit = saveBudget; document.getElementById('resetBudgetBtn').onclick = () => { const state = load(); delete state.budgets[state.settings.currentMonth]; save(state); renderAll(); toast('Budget reset.'); };
  document.getElementById('expenseForm').onsubmit = submitExpense; document.getElementById('splitForm').onsubmit = submitSplit; document.getElementById('settlementForm').onsubmit = submitSettlement; document.getElementById('groupForm').onsubmit = submitGroup;
  document.getElementById('cancelExpenseEdit').onclick = () => { document.getElementById('expenseForm').reset(); delete document.getElementById('expenseForm').dataset.editId; document.getElementById('expenseFormTitle').textContent = 'Add expense'; document.getElementById('cancelExpenseEdit').classList.add('hidden'); };
  document.getElementById('expenseList').onclick = handleActions; document.getElementById('splitSummary').onclick = handleActions; document.getElementById('settlementList').onclick = handleActions;
  document.getElementById('demoDataBtn').onclick = loadDemo; document.getElementById('exportDataBtn').onclick = exportData; document.getElementById('importDataInput').onchange = importData;
  document.getElementById('clearDataBtn').onclick = () => { if (confirm('Delete all local SplitMate data?')) { localStorage.removeItem(STORAGE_KEY); renderAll(); toast('All local data cleared.'); } };
  document.getElementById('currentUserInput').onchange = (e) => { const state = load(); state.settings.currentUser = e.target.value.trim() || 'Akash'; save(state); renderAll(); };
  document.querySelectorAll('.nav-btn').forEach((button) => button.onclick = () => { document.querySelectorAll('.view').forEach((view) => view.classList.toggle('active', view.id === button.dataset.view)); document.querySelectorAll('.nav-btn').forEach((item) => item.classList.toggle('active', item === button)); });
}
window.addEventListener('DOMContentLoaded', () => { const state = load(); save(state); bind(); renderAll(); });
window.addEventListener('storage', renderAll);
